-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS practica02.espacios
(
    id serial,
    ubicacion text,
    estatus practica02.estatus_nombre,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica02.personas
(
    id serial,
    nombre character varying(80),
    apellido character varying(80),
    tipo practica02.persona_tipos,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica02.reservas
(
    id serial,
    espacio_id integer,
    persona_id integer,
    evento text,
    inicio_fecha_hora timestamp without time zone DEFAULT NOW(),
    fin_fecha_hora timestamp without time zone DEFAULT NOW(),
    estatus practica02.reserva_estatus,
    tiempo_reserva interval GENERATED ALWAYS AS (fin_fecha_hora - inicio_fecha_hora) STORED,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS practica02.reservas
    ADD FOREIGN KEY (persona_id)
    REFERENCES practica02.personas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica02.reservas
    ADD FOREIGN KEY (espacio_id)
    REFERENCES practica02.espacios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;