-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.proveedores_1
(
    id serial,
    nombre character varying(80),
    direccion text,
    telefono character varying(40),
    correo_electronico character varying(80),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos_1
(
    id serial,
    proveedor_id integer,
    nombre character varying(80),
    existencia integer,
    precio numeric(13, 2),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.productos_1
    ADD FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores_1 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;