-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS practica01.categorias
(
    id serial,
    nombre text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.etiquetas
(
    id serial,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.roles
(
    id serial,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.imagenes
(
    id serial,
    producto_id integer,
    archivo text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.usuarios
(
    id serial,
    cedula character varying(10),
    nombre character varying(100),
    apellido character varying(100),
    telefono character varying(20)[],
    correo_electronico text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.usuarios_roles
(
    usuario_id integer,
    rol_id integer,
    PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS practica01.productos
(
    id serial,
    categoria_id integer,
    nombre text,
    cantidad integer,
    precio numeric(13, 2),
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.calificaciones
(
    id serial,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica01.productos_calificaciones
(
    producto_id integer,
    calificacion_id integer,
    usuario_id integer,
    PRIMARY KEY (producto_id, calificacion_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS practica01.productos_etiquetas
(
    producto_id integer,
    etiqueta_id integer,
    PRIMARY KEY (producto_id, etiqueta_id)
);

ALTER TABLE IF EXISTS practica01.imagenes
    ADD FOREIGN KEY (producto_id)
    REFERENCES practica01.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.usuarios_roles
    ADD FOREIGN KEY (usuario_id)
    REFERENCES practica01.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.usuarios_roles
    ADD FOREIGN KEY (rol_id)
    REFERENCES practica01.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos
    ADD FOREIGN KEY (categoria_id)
    REFERENCES practica01.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos_calificaciones
    ADD FOREIGN KEY (producto_id)
    REFERENCES practica01.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos_calificaciones
    ADD FOREIGN KEY (calificacion_id)
    REFERENCES practica01.calificaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos_calificaciones
    ADD FOREIGN KEY (usuario_id)
    REFERENCES practica01.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos_etiquetas
    ADD FOREIGN KEY (producto_id)
    REFERENCES practica01.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica01.productos_etiquetas
    ADD FOREIGN KEY (etiqueta_id)
    REFERENCES practica01.etiquetas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;