-- Ejemplo de asociaciones de muchos a muchos

-- Se tiene la entidad estudiantes y asignaturas

create table estudiantes(
    id integer unsigned auto_increment,
    nombre varchar(40),
    apellido varchar(40),
    primary key(id)
);

create table asignaturas(
    id integer unsigned auto_increment,
    nombre varchar(40),
    area text,
    primary key(id)
);

-- Tabla asociativa estudiantes_asignaturas
create table estudiantes_asignaturas(
    estudiante_id integer unsigned,
    asignatura_id integer unsigned,
    periodo_del_curso integer(4) unsigned,
    nota integer(2) unsigned,
    primary key(estudiante_id, asignatura_id, periodo_del_curso),
    foreign key(estudiante_id) references estudiantes(id) on update cascade,
    foreign key(asignatura_id) references asignaturas(id) on update cascade 
);

-- incorporación del atributo auto_increment en la tabla estudiantes
alter table estudiantes modify id integer unsigned auto_increment;

-- incorporación del atributo auto_increment en la tabla asignaturas
alter table asignaturas modify id integer unsigned auto_increment;
alter table estudiantes_asignaturas modify nota integer(3) unsigned;

-- Sembrado de datos

insert into estudiantes(nombre, apellido)
values
('JOSE', 'MEDINA'),
('RICARDO', 'SILVA'),
('ANDRES', 'FRANCO');

insert into asignaturas(nombre, area) values
('LÓGICA DE PROGRAMACIÓN', 'PROGRAMACIÓN'),
('MYSQL', 'BASES DE DATOS'),
('POSTGRESQL', 'BASES DE DATOS'),
('HTML', 'DESARROLLO WEB'),
('JAVASCRIPT', 'DESARROLLO WEB'),
('PHP', 'DESARROLLO WEB'),
('PYTHON', 'PROGRAMACIÓN');

INSERT INTO estudiantes_asignaturas(estudiante_id, asignatura_id, periodo_del_curso, nota) values
(1,1,2025,80),
(1,2,2026,100),
(1,4,2025,90),
(2,1,2025,90),
(2,2,2026,85),
(2,4,2025,100),
(3,1,2025,95),
(3,2,2026,100),
(3,4,2025,100);

-- CONSULTA COMBINADAS 
SELECT PROVEEDORES.NOMBRE AS PROVEEDOR,
       PRODUCTOS.NOMBRE AS PRODUCTO,
       PRODUCTOS.CANTIDAD,
       PRODUCTOS.PRECIO
FROM PROVEEDORES, PRODUCTOS
WHERE PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID;

-- LOS ALIAS TAMBIÉN PUEDEN SER EMPLEADOS PARA 
-- LOS NOMBRES DE LAS TABLAS, POR EJEMPLO:
SELECT A.NOMBRE AS PROVEEDOR,
       B.NOMBRE AS PRODUCTO,
       B.CANTIDAD,
       B.PRECIO
FROM PROVEEDORES AS A, PRODUCTOS AS B
WHERE A.ID = B.PROVEEDOR_ID;

-- CONSULTA DE LAS TRES TABLAS ASOCIADAS
SELECT A.NOMBRE AS NOMBRE_ESTUDIANTE,
       A.APELLIDO AS APELLIDO_ESTUDIANTE,
       B.NOMBRE AS NOMBRE_ASIGNATURA,
       C.PERIODO_DEL_CURSO AS PERIODO,
       C.NOTA AS NOTA
FROM ESTUDIANTES AS A,
    ASIGNATURAS AS B,
    ESTUDIANTES_ASIGNATURAS AS C
    WHERE A.ID = C.ESTUDIANTE_ID AND 
          B.ID = C.ASIGNATURA_ID;


INSERT INTO estudiantes_asignaturas(estudiante_id, asignatura_id, periodo_del_curso, nota) values
(1,1,2026,90);

-- CREACIÓN DE VISTA PARA CONSULTA DE ESTUDIANTES Y ASIGNATURAS
CREATE VIEW vista_estudiantes_asignaturas AS
SELECT A.NOMBRE AS NOMBRE_ESTUDIANTE,
       A.APELLIDO AS APELLIDO_ESTUDIANTE,
       B.NOMBRE AS NOMBRE_ASIGNATURA,
       C.PERIODO_DEL_CURSO AS PERIODO,
       C.NOTA AS NOTA
FROM ESTUDIANTES AS A,
    ASIGNATURAS AS B,
    ESTUDIANTES_ASIGNATURAS AS C
    WHERE A.ID = C.ESTUDIANTE_ID AND 
          B.ID = C.ASIGNATURA_ID;

-- CONSULTA DEL RESULTADO DE LA VISTA
SELECT * FROM vista_estudiantes_asignaturas;


-- CONSULTA DE 2 TABLAS ASOCIADAS CON JOIN 
-- PROVEEDORES Y PRODUCTOS

-- (1) INNER JOIN
SELECT PROVEEDORES.NOMBRE AS PROVEEDOR,
       PRODUCTOS.NOMBRE AS PRODUCTO,
       PRODUCTOS.CANTIDAD,
       PRODUCTOS.PRECIO
FROM PROVEEDORES
INNER JOIN PRODUCTOS ON PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID;

-- INNER JOIN GUARDADO COMO VISTA
CREATE VIEW vista_inner_join_proveedores_productos AS
SELECT PROVEEDORES.NOMBRE AS PROVEEDOR,
       PRODUCTOS.NOMBRE AS PRODUCTO,
       PRODUCTOS.CANTIDAD,
       PRODUCTOS.PRECIO
FROM PROVEEDORES
INNER JOIN PRODUCTOS ON PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID;

-- (2) LEFT JOIN 
-- SE VAN A AÑADIR 3 NUEVOS PROVEEDORES QUE NO TIENEN PRODUCTOS
INSERT INTO PROVEEDORES(NOMBRE, DIRECCION, TELEFONO, CORREO_ELECTRONICO) VALUES
('PHILIPS', 'PLAZA VENEZUELA', '2125673421', 'info@philips.com'),
('SAMSUNG', 'BOLEITA NORTES', '2129872323', 'info@samsung.com'),
('WHIRLPOOL', 'LA CALIFORNIA', '2124417889', 'info@whirlpool.com');

SELECT PROVEEDORES.NOMBRE AS PROVEEDOR,
       PRODUCTOS.NOMBRE AS PRODUCTO,
       PRODUCTOS.CANTIDAD,
       PRODUCTOS.PRECIO
FROM PROVEEDORES
LEFT JOIN PRODUCTOS ON PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID;

-- LEFT JOIN GUARDADO COMO VISTA
CREATE VIEW vista_left_join_proveedores_productos AS
SELECT PROVEEDORES.NOMBRE AS PROVEEDOR,
       PRODUCTOS.NOMBRE AS PRODUCTO,
       PRODUCTOS.CANTIDAD,
       PRODUCTOS.PRECIO
FROM PROVEEDORES
LEFT JOIN PRODUCTOS ON PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID;


-- RIGHT JOIN
-- SE VAN A AÑADIR 3 NUEVOS PRODUCTOS QUE NO TIENEN PROVEEDORES
-- PREPARCIÓN DE TABLAS SECUNCIALES PARA EL RIGHT JOIN
CREATE TABLE PROVEEDORES_SECUENCIAL(
    ID INTEGER UNSIGNED AUTO_INCREMENT,
    NOMBRE VARCHAR(40),
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO_ELECTRONICO VARCHAR(50),
    PRIMARY KEY(ID)
);

CREATE TABLE PRODUCTOS_SECUENCIAL(
    ID INTEGER UNSIGNED AUTO_INCREMENT,
    PROVEEDOR_ID INTEGER UNSIGNED,
    NOMBRE VARCHAR(40),
    CANTIDAD INTEGER UNSIGNED,
    PRECIO DECIMAL(10,2),
    PRIMARY KEY(ID)
);

INSERT INTO proveedores_secuencial(nombre, direccion, telefono, correo_electronico) VALUES
('GENERAL ELECTRIC','AV. LECUNA','2121112233','info@ge.com'),
('LG','AV. ROMULO GALLEGOS','2121112277','info@lg.com'),
('MABE','AV. FCO. DE MIRANDA','2123334455','info@mabe.com'),
('PHILIPS', 'PLAZA VENEZUELA', '2125673421', 'info@philips.com'),
('SAMSUNG', 'BOLEITA NORTES', '2129872323', 'info@samsung.com'),
('WHIRLPOOL', 'LA CALIFORNIA', '2124417889', 'info@whirlpool.com');

INSERT INTO productos_secuencial(proveedor_id, nombre, cantidad, precio) VALUES
(1,'NEVERA',6,500.25),
(1,'COCINA',3,300.75),
(2,'LAVADORA',2,800.50),
(3,'AIRE ACONDICIONADO',4,600.75),
(3,'TELEVISOR',7,400.00),
(3,'LAPTOP',5,1200.00),
(2,'MICROONDAS',8,150.25),
(1,'LICUADORA',12,100.00),
(2,'PLANCHA',12,75.50),
(3,'VENTILADOR',12,50.00),
(1,'HORNO A GAS',6,450.00),
(2,'CAFETERA',12,250.00),
(3,'TOSTADORA',12,80.00),
(15,'SECADORA',5,300.00),
(15,'TELEVISOR 4K',3,1200.00),
(15,'LAVAVAJILLAS',4,700.00),
(16,'TELEVISOR CURVO',2,1500.00),
(16,'AURICULARES',10,200.00),
(16,'TABLET',6,400.00),
(17,'LAVADORA INDUSTRIAL',1,2500.00),
(17,'SECADORA INDUSTRIAL',1,2000.00),
(17,'REFRIGERADOR INDUSTRIAL',1,3000.00);

-- AHORA SI EL RIGHT JOIN
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
RIGHT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID;


CREATE VIEW vista_right_join_proveedores_productos AS
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
RIGHT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID;

-- FULL JOIN
-- EN MYSQL NO EXISTE EL FULL JOIN, POR LO QUE SE DEBE 
-- SIMULAR CON LA UNION DE UN LEFT JOIN Y UN RIGHT JOIN
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
LEFT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID
UNION
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
RIGHT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID;

CREATE VIEW vista_full_join_proveedores_productos AS
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
LEFT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID
UNION
SELECT PROVEEDORES_SECUENCIAL.NOMBRE AS PROVEEDOR,
       PRODUCTOS_SECUENCIAL.NOMBRE AS PRODUCTO,
       PRODUCTOS_SECUENCIAL.CANTIDAD,
       PRODUCTOS_SECUENCIAL.PRECIO
FROM PROVEEDORES_SECUENCIAL
RIGHT JOIN PRODUCTOS_SECUENCIAL ON PROVEEDORES_SECUENCIAL.ID = PRODUCTOS_SECUENCIAL.PROVEEDOR_ID;

-- COLUMNAS CALCULADAD
SELECT SUM(CAMPO)...;
-- POR EJEMPLO:
SELECT SUM(CANTIDAD) FROM vista_full_join_proveedores_productos;

SELECT MIN(CAMPO)...;
-- POR EJEMPLO:
SELECT MIN(PRECIO) FROM vista_full_join_proveedores_productos;

SELECT MAX(CAMPO)...;
-- POR EJEMPLO:
SELECT MAX(PRECIO) FROM vista_full_join_proveedores_productos;

SELECT AVG(CAMPO)...;
-- POR EJEMPLO:
SELECT AVG(PRECIO) FROM vista_full_join_proveedores_productos;

SELECT ROUND(AVG(PRECIO),2) FROM vista_full_join_proveedores_productos;

-- CASO CONTAR, SE DA SOBRE LOS VALORES CONTENIDOS 
-- EN EL CAMPO DIFERENTE DE NULL, POR LO QUE SI EXISTEN 
-- VALORES NULL NO SE CONTARÁN 
SELECT COUNT(CAMPO)...;

SELECT COUNT(PROVEEDOR) FROM vista_full_join_proveedores_productos;

-- EN CASO DE REEMPLAZA EL NOMBRE DEL CAMPO POR *, SI CONTARÁ TODOS LOS REGISTROS, INCLUYENDO LOS VALORES NULL
SELECT COUNT(*) FROM vista_full_join_proveedores_productos;

-- OTRAS FUNCIONES
-- DESDE LA TERMINAL DE MYSQL SE PUEDEN EJECUTAR FUNCIONES COMO:
-- HELP FUNCTIONS Y REVISAR CADA SUB GRUPO DE FUNCIONES, POR EJEMPLO:
-- HELP STRING FUNCTIONS

-- ORDENAMIENTO DE REGISTROS
-- ASCENDENTE
SELECT * FROM vista_inner_join_proveedores_productos 
ORDER BY PROVEEDOR ASC;
-- DESCENDENTE
SELECT * FROM vista_inner_join_proveedores_productos 
ORDER BY PROVEEDOR DESC;

-- OTRO CASO
SELECT * FROM vista_full_join_proveedores_productos 
ORDER BY CANTIDAD ASC, PRECIO ASC;
-- DESCENDENTE
SELECT * FROM vista_full_join_proveedores_productos 
ORDER BY CANTIDAD DESC, PRECIO DESC;








