-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS practica02.espacios
(
    id serial NOT NULL,
    ubicacion text COLLATE pg_catalog."default",
    estatus practica02.estatus_nombre,
    CONSTRAINT espacios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica02.personas
(
    id serial NOT NULL,
    nombre character varying(80) COLLATE pg_catalog."default",
    apellido character varying(80) COLLATE pg_catalog."default",
    tipo practica02.persona_tipos,
    CONSTRAINT personas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS practica02.reservas
(
    id serial NOT NULL,
    espacio_id integer,
    persona_id integer,
    evento text COLLATE pg_catalog."default",
    inicio_fecha_hora timestamp without time zone DEFAULT now(),
    fin_fecha_hora timestamp without time zone DEFAULT now(),
    estatus practica02.reserva_estatus,
    CONSTRAINT reservas_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS practica02.reservas
    ADD CONSTRAINT reservas_espacio_id_fkey FOREIGN KEY (espacio_id)
    REFERENCES practica02.espacios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS practica02.reservas
    ADD CONSTRAINT reservas_persona_id_fkey FOREIGN KEY (persona_id)
    REFERENCES practica02.personas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;