-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.proveedores_1
(
    id serial,
    nombre character varying(80),
    direccion text,
    telefono character varying(40),
    correo character varying(80),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos_1
(
    id serial,
    proveedor_id integer,
    nombre character varying(80),
    cantidad integer,
    precio numeric(13, 2),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alumno
(
    id serial,
    nombre character varying(80),
    apellido character varying(80),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asignaturas
(
    id serial,
    nombre character varying(80),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alumnos_asignaturas_inscripcion
(
    alumno_id integer,
    asignatura_id integer,
    periodo smallint,
    PRIMARY KEY (alumno_id, asignatura_id, periodo)
);

ALTER TABLE IF EXISTS public.productos_1
    ADD FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores_1 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alumnos_asignaturas_inscripcion
    ADD FOREIGN KEY (alumno_id)
    REFERENCES public.alumno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alumnos_asignaturas_inscripcion
    ADD FOREIGN KEY (asignatura_id)
    REFERENCES public.asignaturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;